version: "3.8"

services:
  date-annotator:
    image: nlpsandbox/date-annotator-example-java:latest
    build:
      context: server
      dockerfile: Dockerfile
    container_name: date-annotator-example-java
    ports:
      - "8080:8080"
